"""add scrapeitem sequence

Revision ID: 18c07ad344ca
Revises: 4326e37233b2
Create Date: 2026-07-08 11:03:55.958092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18c07ad344ca'
down_revision: Union[str, None] = '4326e37233b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scrape_items', sa.Column('sequence', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_scrape_items_sequence'), 'scrape_items', ['sequence'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scrape_items_sequence'), table_name='scrape_items')
    op.drop_column('scrape_items', 'sequence')
    # ### end Alembic commands ###
