"""baseline schema

Revision ID: 4326e37233b2
Revises: 
Create Date: 2026-07-08 10:27:49.290136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4326e37233b2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disk_samples',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('free_bytes', sa.BigInteger(), nullable=False),
    sa.Column('bytes_in_rate', sa.Float(), nullable=False),
    sa.Column('bytes_out_rate', sa.Float(), nullable=False),
    sa.Column('hours_to_full', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disk_samples_ts'), 'disk_samples', ['ts'], unique=False)
    op.create_table('settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('PUBLIC', 'FREE', 'PAID', 'ADMIN', name='userrole', native_enum=False, length=20), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('credit_balance', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_log',
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('actor_ip', sa.String(length=45), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_ts'), 'audit_log', ['ts'], unique=False)
    op.create_table('cms_pages',
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('content_md', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('slug')
    )
    op.create_table('platform_credentials',
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('kind', sa.Enum('API_KEY', 'OAUTH_TOKEN', 'COOKIE', name='credentialkind', native_enum=False, length=20), nullable=False),
    sa.Column('secret_blob', sa.Text(), nullable=False),
    sa.Column('added_by', sa.UUID(), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_credentials_platform'), 'platform_credentials', ['platform'], unique=False)
    op.create_table('scrapes',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'PARTIAL', 'CANCELLED', 'FAILED', 'EXPIRED', name='scrapestatus', native_enum=False, length=20), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('share_token', sa.String(length=64), nullable=False),
    sa.Column('total_images', sa.Integer(), nullable=False),
    sa.Column('total_videos', sa.Integer(), nullable=False),
    sa.Column('total_bytes', sa.BigInteger(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('proxy_used', sa.Boolean(), nullable=False),
    sa.Column('ua_used', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scrapes_expires_at'), 'scrapes', ['expires_at'], unique=False)
    op.create_index(op.f('ix_scrapes_share_token'), 'scrapes', ['share_token'], unique=True)
    op.create_index(op.f('ix_scrapes_user_id'), 'scrapes', ['user_id'], unique=False)
    op.create_table('categories',
    sa.Column('scrape_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['scrape_id'], ['scrapes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_scrape_id'), 'categories', ['scrape_id'], unique=False)
    op.create_table('lawful_attestations',
    sa.Column('scrape_id', sa.UUID(), nullable=False),
    sa.Column('text_version', sa.String(length=50), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('actor_ip', sa.String(length=45), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['scrape_id'], ['scrapes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lawful_attestations_scrape_id'), 'lawful_attestations', ['scrape_id'], unique=True)
    op.create_table('usage_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('scrape_id', sa.UUID(), nullable=True),
    sa.Column('links_count', sa.Integer(), nullable=False),
    sa.Column('bytes', sa.BigInteger(), nullable=False),
    sa.Column('proxy_bytes', sa.BigInteger(), nullable=False),
    sa.Column('exit_ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scrape_id'], ['scrapes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_events_ip'), 'usage_events', ['ip'], unique=False)
    op.create_index(op.f('ix_usage_events_user_id'), 'usage_events', ['user_id'], unique=False)
    op.create_table('scrape_items',
    sa.Column('scrape_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SCRAPING', 'SUCCESS', 'PARTIAL', 'FAILED', name='scrapeitemstatus', native_enum=False, length=20), nullable=False),
    sa.Column('images_found', sa.Integer(), nullable=False),
    sa.Column('images_ok', sa.Integer(), nullable=False),
    sa.Column('videos_found', sa.Integer(), nullable=False),
    sa.Column('videos_ok', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['scrape_id'], ['scrapes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scrape_items_category_id'), 'scrape_items', ['category_id'], unique=False)
    op.create_index(op.f('ix_scrape_items_scrape_id'), 'scrape_items', ['scrape_id'], unique=False)
    op.create_table('media_files',
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('IMAGE', 'VIDEO', name='mediatype', native_enum=False, length=10), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('bytes', sa.BigInteger(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_method', sa.Enum('API', 'YTDLP', 'GALLERYDL', 'PLAYWRIGHT', name='sourcemethod', native_enum=False, length=20), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['scrape_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_files_category_id'), 'media_files', ['category_id'], unique=False)
    op.create_index(op.f('ix_media_files_checksum'), 'media_files', ['checksum'], unique=False)
    op.create_index(op.f('ix_media_files_item_id'), 'media_files', ['item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_files_item_id'), table_name='media_files')
    op.drop_index(op.f('ix_media_files_checksum'), table_name='media_files')
    op.drop_index(op.f('ix_media_files_category_id'), table_name='media_files')
    op.drop_table('media_files')
    op.drop_index(op.f('ix_scrape_items_scrape_id'), table_name='scrape_items')
    op.drop_index(op.f('ix_scrape_items_category_id'), table_name='scrape_items')
    op.drop_table('scrape_items')
    op.drop_index(op.f('ix_usage_events_user_id'), table_name='usage_events')
    op.drop_index(op.f('ix_usage_events_ip'), table_name='usage_events')
    op.drop_table('usage_events')
    op.drop_index(op.f('ix_lawful_attestations_scrape_id'), table_name='lawful_attestations')
    op.drop_table('lawful_attestations')
    op.drop_index(op.f('ix_categories_scrape_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_scrapes_user_id'), table_name='scrapes')
    op.drop_index(op.f('ix_scrapes_share_token'), table_name='scrapes')
    op.drop_index(op.f('ix_scrapes_expires_at'), table_name='scrapes')
    op.drop_table('scrapes')
    op.drop_index(op.f('ix_platform_credentials_platform'), table_name='platform_credentials')
    op.drop_table('platform_credentials')
    op.drop_table('cms_pages')
    op.drop_index(op.f('ix_audit_log_ts'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('settings')
    op.drop_index(op.f('ix_disk_samples_ts'), table_name='disk_samples')
    op.drop_table('disk_samples')
    # ### end Alembic commands ###
